sudo: true
language: rust
cache: cargo
rust:
  - nightly
  - nightly-2017-01-25
  - beta
  - stable
  - 1.11.0
matrix:
    allow_failures:
        - rust: nightly
before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - cargo test -- --verbose
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
